import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/query-provider";
import {GoogleOAuthProvider} from '@react-oauth/google';
import Sidebar from "@/components/Sidebar";
import InitAuth from "@/components/InitAuth";

const CLIENTID = process.env.NEXT_GOOGLE_CLIENT_ID!;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen bg-[#D8DEEC]`}
      >
        <GoogleOAuthProvider clientId={CLIENTID}>
          <QueryProvider>
            {/* <InitAuth /> */}
            {/* <Sidebar /> */}
            <main className="flex-1">{children}</main>
          </QueryProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
